// Generated by CoffeeScript 1.9.3

/*-------------------------------------------------------------------------------------------------------------------*\
|  Copyright (C) 2015 PayPal                                                                                          |
|                                                                                                                     |
|  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance     |
|  with the License.                                                                                                  |
|                                                                                                                     |
|  You may obtain a copy of the License at                                                                            |
|                                                                                                                     |
|       http://www.apache.org/licenses/LICENSE-2.0                                                                    |
|                                                                                                                     |
|  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed   |
|  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for  |
|  the specific language governing permissions and limitations under the License.                                     |
\*-------------------------------------------------------------------------------------------------------------------
 */
'use strict';
var AccountsController, app, bodyParser, db, engine, express, mongoose, path, renderer, server;

require('node-jsx').install();

path = require('path');

express = require('express');

renderer = require('react-engine');

bodyParser = require('body-parser');

mongoose = require('mongoose');

app = express();

mongoose.connect('mongodb://localhost/yokoso');

db = mongoose.connection;

db.once('open', function(callback) {});

engine = renderer.server.create({
  routes: require('./public/routes')
});

app.engine('.jsx', engine);

app.engine('.js', engine);

app.set('views', __dirname + '/public/views');

app.set('view engine', 'jsx');

app.set('view', renderer.expressView);

app.use(express["static"](__dirname + '/public'));

app.use(require('connect-livereload')());

app.use(bodyParser.urlencoded({
  extended: false
}));

app.get('/', function(req, res) {
  res.render(req.url, {
    title: 'Yokoso'
  });
});

app.get('/sign_up', function(req, res) {
  res.render(req.url, {
    title: 'Sign up - Yokoso'
  });
});

app.get('/sign_in', function(req, res) {
  res.render(req.url, {
    title: 'Sign in - Yokoso'
  });
});

AccountsController = require('./dest/controllers/accounts_controller')(app, mongoose);

app.use(function(req, res) {
  res.render('404.js', {
    title: 'React Engine Express Sample App',
    url: req.url
  });
});

server = app.listen(3000, function() {
  var host, port;
  host = server.address().address;
  port = server.address().port;
  console.log('App listening at http://%s:%s', host, port);
});
